#Shimeji-ee Configuration Options
#Fri Jan 17 14:16:15 SGT 2025
Filter=nearest
Opacity=1.0
Breeding=true
BackgroundMode=centre
BackgroundImage=
Transformation=true
MenuDPI=96
Transients=true
WindowSize=600x500
InteractiveWindows=Chat/Notepad/Friends/Windows Live Messenger/Clip Studio Paint/Opera GX Internet Browser/Windows Explorer/Spotify/CLIP STUDIO PAINT/Anytype/Calculator
Scaling=1.0
Environment=generic
AlwaysShowShimejiChooser=false
ActiveShimeji=Alastor
Background=\#FFAED7
AlwaysShowInformationScreen=false
