#Shimeji-ee Configuration Options
#Sat Jun 28 01:40:54 PDT 2025
Filter=nearest
Opacity=1.0
Breeding=true
MenuDPI=96
Throwing=true
InteractiveWindows=Chat/Notepad/Friends/Windows Live Messenger/a/e/u/i/o
Environment=generic
AlwaysShowShimejiChooser=false
Scaling=2.0
ActiveShimeji=Tenna
AlwaysShowInformationScreen=false
