#Shimeji-ee Configuration Options
#Sun Jan 26 07:35:56 SGT 2025
Filter=nearest
Opacity=1.0
Breeding=true
BackgroundMode=centre
BackgroundImage=
Transformation=true
MenuDPI=96
Transients=true
WindowSize=600x500
InteractiveWindows=Chat/Notepad/Friends/Windows Live Messenger/Clip Studio Paint/Opera GX Internet Browser/Windows Explorer/Spotify/CLIP STUDIO PAINT/Anytype/Calculator
AlwaysShowShimejiChooser=false
Environment=generic
Scaling=1.0
ActiveShimeji=Lucifer
AlwaysShowInformationScreen=false
Background=\#FFAED7
