#Shimeji-ee Configuration Options
#Wed May 04 08:01:23 BOT 2022
MenuDPI=120
InteractiveWindows=Chat/Notepad/Friends/Windows Live Messenger/Firefox
Breeding=false
ActiveShimeji=hornet
Multiscreen=true
Sounds=false
